export const API_URL = "https://apiclone.instacash.land/api/";

export const NetworkConfiguration = {
  USERREPORT: "admin/allfindReport",
  HOSTREPORT: "admin/allfindHostReports",
  SUSPENDEDUSER: "admin/getListUserSuspended",
  SUSPENDEDHOST: "admin/getListHostSuspended",
  SUSPENDHOST: "admin/adminSuspendHost",
  WARNEDHOST: "admin/getWaringHostList",
  WARNEDUSER: "admin/getWaringUserList",
  GETBANNER: "banner/getAllBanner",
  ACCEPTEDHOST: "admin/getAllAcceptHost",
  GETLEADER: "admin/getAllLeader",
  REJECTEDHOST: "admin/getHostRejected",
  GETHOSTFEEDBACK: "admin/getAdminHostFeedback",
  GETUSERFEEDBACK: "admin/getAdminUserFeedback",
  GETUSERS: "admin/getUsersPending",
  GETGIFT: "gift/getAllGift",
  GETSTICKER: "sticker/adminFindAllSticker",
  ADDGIFT: "gift/addGiftPicture",
  GETUSERMOMENT: "admin/adminFindUserMoment",
  DELETEUSER: "admin/adminDeletedUser",
  DELETEUSERMOMENT: "admin/adminDeletedUserMoment",
  DELETEGIFT: "gift/giftDelete",
  DELETEBANNER: "banner/bannerDelete",
  DELETEWARNING: "admin/adminDeleteWarning",
  DELETESUSPENSION: "admin/adminDeleteSuspended",
  DELETEHOST: "admin/adminDeletedHost",
};
